### ISSUE TITLE
profile manager Mnemonics removal or inserting another account info 

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/grid_weblets#1286] opened 2023-02-06 06:59 UTC
### Description

once you login the profile manager even if you remove the Mnemonics the user data is not removed
![image](https://user-images.githubusercontent.com/110984055/216900427-cfc86447-e694-469a-8cfc-cfbf5157cc3d.png)

### Steps to reproduce

1. go to the playground
2. use your Mnemonics to login
3. the user data will be shown
4. remove the Mnemonics
5. the user data is still there but you can not make any deployment

![image](https://user-images.githubusercontent.com/110984055/216901106-f5f5c357-c2c0-4174-979a-16103e170cba.png)

[Screencast from 02-06-2023 08:35:17 AM.webm](https://user-images.githubusercontent.com/110984055/216900916-1efa1b38-7658-40ef-bc1f-8119fc379b9a.webm)

inserting another account info
1. go to the playground
2. use your Mnemonics to login
3. the user data will be shown
4. remove the Mnemonics
5. insert the other account Mnemonics
6. the user data of the first account is the still shown
7. you still can not deploy

[Screencast from 02-06-2023 08:54:31 AM.webm](https://user-images.githubusercontent.com/110984055/216904029-9ab0dd43-8697-4310-94cb-4a1c3b398ff7.webm)

**Comment by zaelgohary** [comment] 2023-02-14 10:24
The issue exists on devnet but not locally and I'm not sure why. Most profile manager issues were fixed in https://github.com/threefoldtech/grid_weblets/pull/1248

Change mnemonics:

[change_mn.webm](https://user-images.githubusercontent.com/40770501/218706292-45904eac-0043-4771-b04b-09e606fef644.webm)

Remove mnemonics:

[remove_mn.webm](https://user-images.githubusercontent.com/40770501/218706400-90ba513a-1f02-40d1-b52a-c2ae5f9e5e75.webm)

**Comment by MohamedElmdary** [comment] 2023-02-15 09:42
@zaelgohary 
I was able to reproduce this bug
steps: 
1. yarn build:app
2. cd ./dist
3. npx lite-server

**Comment by zaelgohary** [comment] 2023-03-08 11:34
The issue happens because of the JS bundler. I tried to change the configs so the local could match the published code but still couldn’t figure out a way to fix it.

**Comment by mohamedamer453** [comment] 2023-03-20 11:06
Verified on devnet.

The issue was fixed and now the user data is removed upon removing the mnemonics or replacing it with another mnemonic.
 
[TF Playground.webm](https://user-images.githubusercontent.com/101194226/226321739-d1448904-bded-4936-a5ea-60fb3ee9bcd3.webm)

[TF Playground (1).webm](https://user-images.githubusercontent.com/101194226/226321782-be3e6595-f446-4e7f-99c1-187abffcfd3f.webm)

**Closed as completed by mohamedamer453** 2023-03-20 11:06 UTC
Labels: type_bug
