### ISSUE TITLE
Kubernetes deployment with weblets fails

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/grid_weblets#623] opened 2022-03-28 05:55 UTC
The deployment of Kubernetes with weblets fails now (testnet), previously used to work fine without any issues

![weblets_kubernetes_deployment1](https://user-images.githubusercontent.com/65153287/160335028-0638d277-e75a-40c7-ba53-8bb87bca5fa2.png)

**Comment by mohamedamer453** [comment] 2022-05-05 09:45
Verified on testnet weblets v1.4.1-rc2

The issue is fixed on this version of weblets and i successfully deployed a K8s Cluster without any issues.

![image](https://user-images.githubusercontent.com/101194226/166898932-ccaabcb4-0d74-4ec1-9251-44cbdd1a6f4e.png)


Deployment Details
```
{
    "masters": [
        {
            "version": 0,
            "contractId": 4304,
            "nodeId": 3,
            "name": "WR9510aa56",
            "created": 1651743619,
            "status": "ok",
            "message": "",
            "flist": "https://hub.grid.tf/tf-official-apps/threefoldtech-k3s-latest.flist",
            "publicIP": null,
            "planetary": "302:1eb4:b62c:8ba6:4da0:b0f1:bd00:9a84",
            "interfaces": [
                {
                    "network": "NW5233d921",
                    "ip": "10.20.4.2"
                }
            ],
            "capacity": {
                "cpu": 2,
                "memory": 4096
            },
            "mounts": [
                {
                    "name": "WR9510aa56_disk",
                    "mountPoint": "/mnt/data",
                    "size": 107374182400,
                    "state": "ok",
                    "message": ""
                }
            ],
            "env": {
                "SSH_KEY": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC533B35CELELtgg2d7Tsi5KelLxR0FYUlrcTmRRQuTNP9arP01JYD8iHKqh6naMbbzR8+M0gdPEeRK4oVqQtEcH1C47vLyRI/4DqahAE2nTW08wtJM5uiIvcQ9H2HMzZ3MXYWWlgyHMgW2QXQxzrRS0NXvsY+4wxe97MMZs9MDs+d+X15DfG6JffjMHydi+4tHB50WmHe5tFscBFxLbgDBUxNGiwi3BQc1nWIuYwMMV1GFwT3ndyLAp19KPkEa/dffiqLdzkgs2qpXtfBhTZ/lFeQRc60DHCMWExr9ySDbavIMuBFylf/ZQeJXm9dFXJN7bBTbflZIIuUMjmrI7cU5eSuZqAj5l+Yb1mLN8ljmKSIM3/tkKbzXNH5AUtRVKTn+aEPvJAEYtserAxAP5pjy6nmegn0UerEE3DWEV2kqDig3aPSNhi9WSCykvG2tz7DIr0UP6qEIWYMC/5OisnSGj8w8dAjyxS9B0Jlx7DEmqPDNBqp8UcwV75Cot8vtIac= root@mohamed-Inspiron-3576",
                "K3S_TOKEN": "393fbb22",
                "K3S_DATA_DIR": "/mnt/data",
                "K3S_FLANNEL_IFACE": "eth0",
                "K3S_NODE_NAME": "WR9510aa56",
                "K3S_URL": ""
            },
            "entrypoint": "/sbin/zinit init",
            "metadata": "",
            "description": "",
            "corex": false
        }
    ],
    "workers": [
        {
            "version": 0,
            "contractId": 4305,
            "nodeId": 5,
            "name": "WR21aaea3f",
            "created": 1651743636,
            "status": "ok",
            "message": "",
            "flist": "https://hub.grid.tf/tf-official-apps/threefoldtech-k3s-latest.flist",
            "publicIP": null,
            "planetary": "300:9c4a:29ac:6e0b:fd49:8d99:980e:325",
            "interfaces": [
                {
                    "network": "NW5233d921",
                    "ip": "10.20.5.2"
                }
            ],
            "capacity": {
                "cpu": 2,
                "memory": 4096
            },
            "mounts": [
                {
                    "name": "WR21aaea3f_disk",
                    "mountPoint": "/mnt/data",
                    "size": 107374182400,
                    "state": "ok",
                    "message": ""
                }
            ],
            "env": {
                "SSH_KEY": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC533B35CELELtgg2d7Tsi5KelLxR0FYUlrcTmRRQuTNP9arP01JYD8iHKqh6naMbbzR8+M0gdPEeRK4oVqQtEcH1C47vLyRI/4DqahAE2nTW08wtJM5uiIvcQ9H2HMzZ3MXYWWlgyHMgW2QXQxzrRS0NXvsY+4wxe97MMZs9MDs+d+X15DfG6JffjMHydi+4tHB50WmHe5tFscBFxLbgDBUxNGiwi3BQc1nWIuYwMMV1GFwT3ndyLAp19KPkEa/dffiqLdzkgs2qpXtfBhTZ/lFeQRc60DHCMWExr9ySDbavIMuBFylf/ZQeJXm9dFXJN7bBTbflZIIuUMjmrI7cU5eSuZqAj5l+Yb1mLN8ljmKSIM3/tkKbzXNH5AUtRVKTn+aEPvJAEYtserAxAP5pjy6nmegn0UerEE3DWEV2kqDig3aPSNhi9WSCykvG2tz7DIr0UP6qEIWYMC/5OisnSGj8w8dAjyxS9B0Jlx7DEmqPDNBqp8UcwV75Cot8vtIac= root@mohamed-Inspiron-3576",
                "K3S_TOKEN": "393fbb22",
                "K3S_DATA_DIR": "/mnt/data",
                "K3S_FLANNEL_IFACE": "eth0",
                "K3S_NODE_NAME": "WR21aaea3f",
                "K3S_URL": "https://10.20.4.2:6443"
            },
            "entrypoint": "/sbin/zinit init",
            "metadata": "",
            "description": "",
            "corex": false
        }
    ]
}
```

**Closed by mohamedamer453** 2022-05-05 09:45 UTC
