### ISSUE TITLE
Deletion of VM fails on testnet

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/grid_weblets#626] opened 2022-03-28 06:06 UTC
As previous worked fine, now the VM that is currently in the list from the previous deployment cannot be deleted

![weblets_vm_deletion1](https://user-images.githubusercontent.com/65153287/160336160-3f5129a2-c9fa-40ce-b84d-0808c02417bb.png)

**Comment by mohamedamer453** [comment] 2022-05-05 09:56
Verified on testnet weblets v1.4.1-rc2

The issue is fixed on this version of weblets and i successfully deleted multiple deployments without any issues.

**Closed by mohamedamer453** 2022-05-05 09:56 UTC
