### ISSUE TITLE
Add validation for identical inputs for Kubernetes-Workers 

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/grid_weblets#733] opened 2022-05-19 12:56 UTC
Add two workers with identical Name and run deploy
ex. res. : error message  "Workers can't have duplicated name" and Deploy button - disable 
![screenshoteasy - 2022-05-19T153827 196](https://user-images.githubusercontent.com/65153287/169298325-a0b70f8d-a33e-438d-b7b8-1d8c6cb96d6c.png)
"

**Comment by xmonader** [comment] 2022-05-24 05:10
duplicate of https://github.com/threefoldtech/grid_weblets/issues/722

**Closed by xmonader** 2022-05-24 05:10 UTC
