### ISSUE TITLE
Discourse gives bad gateway

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/grid_weblets#1257] opened 2023-01-19 12:12 UTC
### Discourse issue

whenever i deploy a discourse it gives bad gateway
steps to produce:

1. go to the [playground](https://play.dev.grid.tf/#/discourse)
2. login using your profile
3. try deploying a discourse solution

result:

-  you can't ssh on the machine
- the domain gives bad gateway

![Screenshot from 2023-01-19 14-01-29](https://user-images.githubusercontent.com/110984055/213439947-53e7d6c6-c461-44dc-8c4e-52db04bb32e5.png)
![Screenshot from 2023-01-19 14-03-58](https://user-images.githubusercontent.com/110984055/213440003-12d04aa9-d939-43b7-a3b7-82a6377c047f.png)
![Screenshot from 2023-01-19 14-02-41](https://user-images.githubusercontent.com/110984055/213440014-b3f126a8-e7db-4b10-8338-8e6601b0d97c.png)
![Screenshot from 2023-01-19 14-02-34](https://user-images.githubusercontent.com/110984055/213440018-4dc88e25-2298-4308-b991-44c33080eeca.png)

**Comment by Omarabdul3ziz** [comment] 2023-01-25 09:10
The mentioned PR reverting to the old flist till the issue is fixed in the new flist

**Comment by zaelgohary** [comment] 2023-01-25 10:22
Verified. Created 2 Discourse deployments and both are working fine.

![image](https://user-images.githubusercontent.com/40770501/214536444-579925b6-4261-401d-ab95-71f48681b25b.png)


![image](https://user-images.githubusercontent.com/40770501/214538121-c1a82aa3-28f7-4839-bb7f-dfc99fbd3ed7.png)
![image](https://user-images.githubusercontent.com/40770501/214538058-2da24128-c03c-418e-a3a4-d9652eaa8cbf.png)

Note: sometimes the domain responds with gateway timeout but this depends on whether the gateway node selected in the deployment is up or not.

![image](https://user-images.githubusercontent.com/40770501/214537990-91231144-5c8f-4426-8850-cbe7652f9782.png)

**Closed as completed** 2023-01-25 10:25 UTC
Labels: type_bug
