### ISSUE TITLE
Failed to deploy Caprover

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/grid_weblets#1105] opened 2022-11-15 14:45 UTC
### Description

When I tried to create a Caprover deployment, I faced this error

![caprover](https://user-images.githubusercontent.com/40770501/201947923-63c2a2b1-1094-490f-913d-2661957eb2af.png)

### Steps to reproduce

- go to [weblets](https://play.dev.grid.tf/#/)
- create a Caprover deployment

This happens when I try to add a worker while deploying.

**Comment by mohamedamer453** [comment] 2022-11-21 11:44
The issue was reproducible on node `34` on devnet.

![image](https://user-images.githubusercontent.com/101194226/203040372-a7d2f8d3-186d-4e49-b4c5-b411aaff38e8.png)

```
Error: Error: Failed to deploy zmachine with name CRc847ddac on node 34 due to: failed to satisfy required capacity: cannot fulfil required memory size 140750356480 bytes out of usable 139676907930 bytes
```

from the grid proxy by subtracting the used resources from the total resources the node reported `139676907930` free bytes

![image](https://user-images.githubusercontent.com/101194226/203040761-88e37d14-c3f9-4338-8861-07401de9d775.png)

![image](https://user-images.githubusercontent.com/101194226/203040936-e4597866-ee73-4dfa-967b-e5997eccb05c.png)

and when i tried to deploy an instance with `133206` mb of memory the node appeared in the capacity filter and i was able to deploy on it but then i got the error mentioned above.

**Comment by mohamedamer453** [comment] 2022-11-21 11:51
@muhamadazmy The issue was reproducible on another node on devnet when i tried to max out the memory.

**Comment by mohamedamer453** [comment] 2022-11-22 08:54
I tried the flow again on a different node on devnet and here are the full details.

**Node**:	32

**Available Memory from gridproxy**: total - used = 202802905088 - 23501515981 = 179301389107 bytes = 170995.13 mb

**For the node to appear in the capacity filter**: 170495 mb was used (500mb less than the available)

**Deployed with**: 170495mb ram, 10gb disk, 1vCore

**Contract id**: 14574

**Result**: `Error: Error: Failed to deploy zmachine with name CRfe897ea6 on node 32 due to: failed to satisfy required capacity: cannot fulfil required memory size 179850706944 bytes out of usable 176146752308 bytes`

**Full Logs**: https://gist.github.com/mohamedamer453/bb4ebf6a25b6a7d1248b4460f1d67514

**Sent memory from the error message**: 179850706944 bytes = 171519 mb (1024 mb more than the value i deployed with)

**Available memory from the error message**: 176146752308 bytes = 167986.63 mb (3008.5 mb less than calculating the total - used resources from the grid proxy)

**Comment by mohamedamer453** [comment] 2022-11-23 08:26
I tested the flow again on node `34` (the one with the fix) but i also got the same error, however i noticed some differences from the node i tested yesterday in the comment above.

Firstly when i used the same exact value i got from the calculating the available memory from the gridproxy the node appeared in the capacity filter, unlike node `32` where i had to lower the memory by `500mb`

>**For the node to appear in the capacity filter:** 170495 mb was used (500mb less than the available)

Secondly, the available memory that appeared in the error message was the exact as the available memory calculated from the gridproxy. unlike node `32` where the value that appeared was `3008.8mb` less than the calculated value.

>**Available memory from the error message:** 176146752308 bytes = 167986.63 mb (3008.5 mb less than calculating the total - used resources from the grid proxy)

### Full Details from node 34

**Node**:	34

**Available Memory**: total- used = 202806575104 - 52392248934 = 150414326170 bytes = 143446.28 mb

**For the node to appear in the capacity filter**: 143446 mb was used (the exact same value as the available memory)

**Deployed with**: 143446mb ram, 10gb disk, 1vCore

**Contract id**: 14632

**Result: Error**: Error: Failed to deploy zmachine with name CR9cf5ad52 on node 34 due to: failed to satisfy required capacity: cannot fulfil required memory size 151487774720 bytes out of usable 150414326170 bytes

![image](https://user-images.githubusercontent.com/101194226/203500297-e3ffb8f4-05a6-456c-8828-778cfd4c9523.png)


**Full Logs**: https://gist.github.com/mohamedamer453/2f03571b3d0e9ecfeb6a54b0b1b90274

**Sent memory from the error message**:  151487774720 bytes = 144470 mb (1024 mb more than the value i deployed with)

**Available memory from the error message**:  150414326170 bytes = 143446 mb (the exact same value that was calculated from the grid proxy)

**Comment by mohamedamer453** [comment] 2022-11-23 08:46
### Update 

I was able to successfully deploy on node `34` by lowering the memory to `142422mb` which is exactly `1024mb` lower than the available memory mentioned in the comment above.

![image](https://user-images.githubusercontent.com/101194226/203502738-4553ce0c-efb0-47ba-acce-eadce06aa63e.png)

and after the deployment i checked the available memory from the gridproxy and it still had 1gb of memory left. even though it didn't allow me to deploy without lowering this 1gb 
``
202806575104 - 201732540006 = 1074035098 bytes = 1024.28 mb
``

![image](https://user-images.githubusercontent.com/101194226/203503008-6655a26d-3ec8-4531-bf92-18c13633b802.png)

**Comment by muhamadazmy** [comment] 2022-11-23 09:01
this is not a ZOS issue anymore. Seems on deploying, the weblet or the client you are using adding more memory than requested by you. Hence node fails to deploy. The  available memory reported by the node is exactly what u expected (and calculated) from the gridproxy. 

My suggestion to you is to check the weblet code see where it goes wrong and this extra memory is added.

**Comment by mohamedamer453** [comment] 2022-11-23 16:01
Verified on devnet. 

The issue was fixed in https://github.com/threefoldtech/zos/issues/1848 and the 1gb overhead was removed.

And i was able to verify it on `node 34` by having a deployment max out the available memory on the node.

**Available Memory:** total - used = 202806575104 - 49171023462 = 153635551642 bytes = 146518.28 mb

and as seen from the screenshot below the deployment was successful with `146518 mb` of memory.

![image](https://user-images.githubusercontent.com/101194226/203590729-0d9ba297-fc18-435f-a8ad-a4d9d7b50bc3.png)

and after the deployment i checked the node resources from the gridproxt and it was indeed maxed out.

**Memory available after the deployment:**  202806575104 - 202806281830 = 293274 bytes = 0.279688 mb

![image](https://user-images.githubusercontent.com/101194226/203592007-871acc57-28cd-4156-b08e-0c5afd2352f7.png)

**Closed as completed by mohamedamer453** 2022-11-23 16:01 UTC
Labels: type_bug
