### ISSUE TITLE
Backslashes in environment variables get doubled

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/grid_weblets#604] opened 2022-03-15 23:44 UTC
When attempting to pass a backslash through the environment variables tab to a VM, it gets duplicated in the final output.

**Comment by abom** [comment] 2022-03-16 08:39
@AhmedHanafy725 Can you please check if it's related to weblets?

**Comment by abom** [comment] 2022-03-16 09:33
@scottyeager could you please provide an example of key/value pair that causes this?

**Comment by scottyeager** [comment] 2022-03-16 21:59
Thanks @abom. Here's an example:

Key: "test"
Value: "\ \n ab\cd"

Output in deployment json:

**Comment by mohamedamer453** [comment] 2022-05-05 12:54
Tested on devnet.

The issue is still valid I tried to enter the same Key/Value pair mentioned in this issue and the backslashes still get doubled.
```
Key: "test"
Value: "\ \n ab\cd"
```

Output in JSON 

```
    "test": "\\ \\n ab\\cd"
```

However when i SSH to the vm and print the env vars.

the backslashes are not doubled 

```
root@VM96ec10cd:~# cat /proc/1/environ | tr '\0' '\n'
test=\ \n ab\cd
SHLVL=1
HOME=/root
TERM=linux
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
SSH_KEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC533B35CELELtgg2d7Tsi5KelLxR0FYUlrcTmRRQuTNP9arP01JYD8iHKqh6naMbbzR8+M0gdPEeRK4oVqQtEcH1C47vLyRI/4DqahAE2nTW08wtJM5uiIvcQ9H2HMzZ3MXYWWlgyHMgW2QXQxzrRS0NXvsY+4wxe97MMZs9MDs+d+X15DfG6JffjMHydi+4tHB50WmHe5tFscBFxLbgDBUxNGiwi3BQc1nWIuYwMMV1GFwT3ndyLAp19KPkEa/dffiqLdzkgs2qpXtfBhTZ/lFeQRc60DHCMWExr9ySDbavIMuBFylf/ZQeJXm9dFXJN7bBTbflZIIuUMjmrI7cU5eSuZqAj5l+Yb1mLN8ljmKSIM3/tkKbzXNH5AUtRVKTn+aEPvJAEYtserAxAP5pjy6nmegn0UerEE3DWEV2kqDig3aPSNhi9WSCykvG2tz7DIr0UP6qEIWYMC/5OisnSGj8w8dAjyxS9B0Jlx7DEmqPDNBqp8UcwV75Cot8vtIac= root@mohamed-Inspiron-3576
PWD=/

```

**Comment by abom** [comment] 2022-05-12 10:12
I think after @mohamedamer453 investigation, this is not an actual issue?
At the end it reaches the environment without these double backslashes (mostly for escaping single backslashes in strings).

**Comment by mohamedamer453** [comment] 2022-05-12 11:27
Yes, i think it's not really an issue since it reaches the environment correctly and it doesn't cause any errors.
I will close this issue for now but please feel free to reopen this issue if it needs to be changed in the JSON object.

**Closed by mohamedamer453** 2022-05-12 11:27 UTC
