### ISSUE TITLE
Too low priority to replace another transaction Error!

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/grid_weblets#93] opened 2021-12-02 10:06 UTC
![image](https://user-images.githubusercontent.com/31689104/144400957-c22293ae-165a-4741-b969-b4213473d550.png)

```
Key with address: 5FYqGSaXTz6Dftwo5TtoPDWgQEj8QTprsGnwEn9B6ZMZiK9j is loaded.
names: .json,vm_326f31fc,cr_f2e756c3,vm_647a2be3,vm_c460bb82,CR5c3ee4c2
Sending {try 1}: https://gridproxy.dev.grid.tf/twin/18

2021-12-02 12:01:17        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1014: Priority is too low: (264342040 vs 264342040): The transaction has too low priority to replace another transaction already in the pool.
logger.js?eb80:47 2021-12-02 12:01:17             DRR: 1014: Priority is too low: (264342040 vs 264342040): The transaction has too low priority to replace another transaction already in the pool.
logger.js?eb80:47 2021-12-02 12:01:17        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1014: Priority is too low: (264342040 vs 264342040): The transaction has too low priority to replace another transaction already in the pool.
2021-12-02 12:01:17        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1014: Priority is too low: (264342040 vs 264342040): The transaction has too low priority to replace another transaction already in the pool.
2021-12-02 12:01:17             DRR: 1014: Priority is too low: (264342040 vs 264342040): The transaction has too low priority to replace another transaction already in the pool.
2021-12-02 12:01:17        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1014: Priority is too low: (264342040 vs 264342040): The transaction has too low priority to replace another transaction already in the pool.
2021-12-02 12:01:17        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1014: Priority is too low: (264342040 vs 264342040): The transaction has too low priority to replace another transaction already in the pool.
2021-12-02 12:01:17             DRR: 1014: Priority is too low: (264342040 vs 264342040): The transaction has too low priority to replace another transaction already in the pool.
logger.js?eb80:47 2021-12-02 12:01:17        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1014: Priority is too low: (264342040 vs 264342040): The transaction has too low priority to replace another transaction already in the pool.

Sending {try 1}: Success
{retqueue: '55fccdbb-e1d2-4c15-90fd-4f6be0916975'}
Reading {try 1}: https://gridproxy.dev.grid.tf/twin/18/55fccdbb-e1d2-4c15-90fd-4f6be0916975
Reading {try 1}: Success
section tfkvStore method EntryTaken
section system method ExtrinsicSuccess

'[null,null,null,null,null,{"name":"CR5c3ee4c2","publicIp":"185.206.122.47/24","yggIP":"","flist":"https://hub.grid.tf/tf-official-apps/tf-caprover-main.flist","details":{"version":0,"name":"CRLCR5c3ee4c2","created":1638438613,"status":"ok","message":"","flist":"https://hub.grid.tf/tf-official-apps/tf-caprover-main.flist","publicIP":{"ip":"185.206.122.47/24","ip6":"","gateway":"185.206.122.1"},"planetary":false,"yggIP":"","interfaces":[{"network":"NWCR5c3ee4c2","ip":"10.200.4.2"}],"capacity":{"cpu":1,"memory":1024},"mounts":[{"name":"data0","mountPoint":"/var/lib/docker","size":1073741824,"state":"ok","message":""}],"env":{"SWM_NODE_MODE":"leader","CAPROVER_ROOT_DOMAIN":"tet.com","PUBLIC_KEY":"ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMUv2EQUnLL/Ei2+JRR/8EFIOrMxmlVLIc7psOZau6FE engm5081@gmail.com","DEFAULT_PASSWORD":"5c3ee4c2"},"entrypoint":"/sbin/zinit init","metadata":"","description":"caprover leader machine/node"}}]'
```

**Comment by AhmedHanafy725** [comment] 2021-12-05 14:38
This happens when more than one extrinsic is done at the same time, that's a limitation from the blockchain implementation I think
for now, we can prevent users from doing 2 deployments at the same time.

**Comment by waleedhammam** [comment] 2021-12-13 11:28
It's still happening, I'm only deploying funkwhale 
![image](https://user-images.githubusercontent.com/10658229/145804416-8de7ad14-5792-4e43-9c60-e816bee3cb1a.png)

**Comment by abom** [comment] 2021-12-16 11:02
This is a duplicate of #202?

**Closed** 2021-12-16 11:49 UTC
