### ISSUE TITLE
SelectNodeId request /null node on gridproxy

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/grid_weblets#209] opened 2021-12-14 10:54 UTC
![image](https://user-images.githubusercontent.com/31689104/145984983-44cf18b0-0574-48c5-ad69-b5bc8ad3234e.png)

**Comment by MohamedElmdary** [comment] 2021-12-14 11:05
### Fixed
#### PR
https://github.com/threefoldtech/grid_weblets/pull/210

**Comment by waleedhammam** [comment] 2021-12-14 12:58
still an issue on play.dev.grid.tf
![image](https://user-images.githubusercontent.com/10658229/146002727-7ca55ede-825e-4a25-aeb9-47e78235b41b.png)

code on machine
![image](https://user-images.githubusercontent.com/10658229/146002756-37e7e5a8-ee87-4970-b925-9ee59523ce55.png)

**Comment by xmonader** [comment] 2021-12-16 17:21
Closing. couldn't reproduce

**Closed by xmonader** 2021-12-16 17:21 UTC
Labels: priority_major, type_bug
