### ISSUE TITLE
Randomly show error _undefined_ after a success deployment on `devnet`

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/grid_weblets#1317] opened 2023-02-22 12:00 UTC
![image](https://user-images.githubusercontent.com/31689104/220613885-37d59d50-f7b4-4154-974e-3cf072f447d8.png)

I'm not able to reproduce this issue but it appears *randomly* after a successful deployment

**Comment by MohamedElmdary** [comment] 2023-02-28 11:34
Couldn't reproduce this issue

**Comment by AhmedHanafy725** [comment] 2023-03-15 09:19
try it again and if you couldn't reproduce it, please close it

**Comment by mohamedamer453** [comment] 2023-03-19 15:37
After deploying multiple different solutions on different nodes i wasn't able to reproduce this issue, closing it for now but please reopen it if you found a way to reproduce it.

**Closed as completed by mohamedamer453** 2023-03-19 15:37 UTC
Labels: type_bug
