### ISSUE TITLE
Deployment of OwnCloud fails on testnet

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/grid_weblets#625] opened 2022-03-28 06:02 UTC
The deployment of OwnCloud with weblets fails now (testnet), previously used to work fine without any issues. 

When deploying, the process times out and keeps on hanging endlessl

![weblets_owncloud_deployment1](https://user-images.githubusercontent.com/65153287/160335805-23204759-5199-4a3d-b1b1-57e16d551cf3.png)
y

**Comment by mohamedamer453** [comment] 2022-05-05 10:01
Verified on testnet weblets v1.4.1-rc2

The issue is fixed on this version of weblets and i successfully deployed an Owncloud instance without any issues.

![image](https://user-images.githubusercontent.com/101194226/166901632-49358c82-bf8d-4259-90b9-e27b849331ab.png)

Deployment Details
```
{
    "version": 0,
    "contractId": 4308,
    "nodeId": 8,
    "name": "vmfgddtgxee4",
    "created": 1651744633,
    "status": "ok",
    "message": "",
    "flist": "https://hub.grid.tf/samehabouelsaad.3bot/abouelsaad-owncloud-10.9.1.flist",
    "publicIP": null,
    "planetary": "303:a7a4:4321:15b6:ff2f:b3ab:4389:1876",
    "interfaces": [
        {
            "network": "netfgddtgxee4",
            "ip": "10.1.2.2"
        }
    ],
    "capacity": {
        "cpu": 2,
        "memory": 16384
    },
    "mounts": [
        {
            "name": "diskfgddtgxee4",
            "mountPoint": "/var/lib/docker",
            "size": 107374182400,
            "state": "ok",
            "message": ""
        }
    ],
    "env": {
        "SSH_KEY": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC533B35CELELtgg2d7Tsi5KelLxR0FYUlrcTmRRQuTNP9arP01JYD8iHKqh6naMbbzR8+M0gdPEeRK4oVqQtEcH1C47vLyRI/4DqahAE2nTW08wtJM5uiIvcQ9H2HMzZ3MXYWWlgyHMgW2QXQxzrRS0NXvsY+4wxe97MMZs9MDs+d+X15DfG6JffjMHydi+4tHB50WmHe5tFscBFxLbgDBUxNGiwi3BQc1nWIuYwMMV1GFwT3ndyLAp19KPkEa/dffiqLdzkgs2qpXtfBhTZ/lFeQRc60DHCMWExr9ySDbavIMuBFylf/ZQeJXm9dFXJN7bBTbflZIIuUMjmrI7cU5eSuZqAj5l+Yb1mLN8ljmKSIM3/tkKbzXNH5AUtRVKTn+aEPvJAEYtserAxAP5pjy6nmegn0UerEE3DWEV2kqDig3aPSNhi9WSCykvG2tz7DIr0UP6qEIWYMC/5OisnSGj8w8dAjyxS9B0Jlx7DEmqPDNBqp8UcwV75Cot8vtIac= root@mohamed-Inspiron-3576",
        "OWNCLOUD_DOMAIN": "oc451vm8406cc95.gent02.test.grid.tf",
        "OWNCLOUD_ADMIN_USERNAME": "admin",
        "OWNCLOUD_ADMIN_PASSWORD": "123456789",
        "OWNCLOUD_MAIL_SMTP_SECURE": "none",
        "OWNCLOUD_MAIL_DOMAIN": "",
        "OWNCLOUD_MAIL_FROM_ADDRESS": "",
        "OWNCLOUD_MAIL_SMTP_HOST": "",
        "OWNCLOUD_MAIL_SMTP_PORT": "",
        "OWNCLOUD_MAIL_SMTP_NAME": "",
        "OWNCLOUD_MAIL_SMTP_PASSWORD": ""
    },
    "entrypoint": "/sbin/zinit init",
    "metadata": "",
    "description": "",
    "corex": false
}
```

**Closed by mohamedamer453** 2022-05-05 10:01 UTC
