### ISSUE TITLE
Caprover deployment weblet on **main** net does not recognise available capacity on nodes correct

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/grid_weblets#594] opened 2022-03-07 09:27 UTC
Every node ID provided to the caprover weblet to deploy on results on `Node(1318) might be down or doesn't have enough resources.`

While nodes are up and have enough capacity available

**Comment by Omarabdul3ziz** [comment] 2022-03-17 10:27
can't reproduce this on main net.

checking the free resources from https://gridproxy.grid.tf/nodes/nodeId for the nodes marked at `might be down or doesn't have enough resources.` they actually don't have enough resources.

especially for `caprover` and `presearch` if the node does have enough (sru, mru, cru) they maybe don't have public IPs as it is required for these weblets

**Comment by mohamedamer453** [comment] 2022-04-11 12:35
### Devnet

On devnet the issue is still there

After entering the specs for a CapRover deployment the capacity filter shows that there are 14 nodes available to deploy on

![image](https://user-images.githubusercontent.com/101194226/162737826-58ef3d0b-cb33-473b-9a71-336c6d5c7b15.png)

However when trying to enter the node id manually through node selection all the mentioned nodes in the capacity filter give ` might be down or doesn't have enough resources.`

![image](https://user-images.githubusercontent.com/101194226/162738152-40a09af8-9eda-4b2f-9ffe-0be5254cb3c1.png)

Trying to deploy on the same node that gives ` might be down or doesn't have enough resources.` through the capacity filter gives no error and proceeds with the deployment and is deployed successfully.

![image](https://user-images.githubusercontent.com/101194226/162739564-1de4f016-3c69-4d00-888a-85724a377955.png)

![image](https://user-images.githubusercontent.com/101194226/162740005-70ef049d-67a8-4e15-84e4-546dabf1e2b1.png)


### Mainnet

However on mainnet it's working fine

All the nodes provided by the capacity filter are indeed available for deployment when checked manually.

Ex: node 1 is provided by the capacity filter and ready for deployment 

![image](https://user-images.githubusercontent.com/101194226/162735744-82da98ca-bdef-42b7-9b9f-9d343d77eca2.png)

Entering node 1 in the manually through node selection it has enough resources and ready for deployment.

![image](https://user-images.githubusercontent.com/101194226/162735986-8efb43e1-2d8e-412a-96ef-49a35eac071e.png)

**Comment by abom** [comment] 2022-04-28 04:47
Duplicate of https://github.com/threefoldtech/grid_weblets/issues/661

**Closed by abom** 2022-04-28 04:47 UTC
Labels: type_bug
