### ISSUE TITLE
New VM weblet

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#745] opened 2022-05-25 15:42 UTC
### Description

we need to add a new weblet or replace the current VM weblet to deploy these complete VM images from https://hub.grid.tf/tf-official-vms

### Implementation

they require at least one disk which will become the rootfs, and don't need to specify an entry-point.

**Comment by AhmedHanafy725** [comment] 2022-07-17 09:19
duplicate of #759

**Closed by AhmedHanafy725** 2022-07-17 09:19 UTC
Labels: type_feature
