### ISSUE TITLE
CapRover low memory validation - TC411

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/grid_weblets#713] opened 2022-05-17 09:57 UTC
when the resource was deployed with min available disk space with "250" MB it failed with error:
"Validation failed. errors: An instance of k has failed the validation: - property workloads[2].data.compute_capacity.memory has failed the following constraints: min"

when the resource was deployed with min available disk space with "+250" MB it failed with error:
"Validation failed. errors: An instance of k has failed the validation: - property workloads[2].data.compute_capacity.memory has failed the following constraints: min"
Selected Capacity Package - custom
version - v1.4.1-rc2 testnet

**Comment by xmonader** [comment] 2022-05-30 11:30
duplicate of #714

**Closed by xmonader** 2022-05-30 11:30 UTC
