### ISSUE TITLE
Failed weblets deployment after getting versions right?

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/grid_weblets#1141] opened 2022-11-29 11:04 UTC
Still have a filed deployment for Kubernetes:
```
$ yarn build && sh scripts/build.sh && cd playground && yarn serve --host 45.156.243.209
$ rollup -c

src/elements/ContractsList/index.ts → .build/build/elements/contractslist.wc.js...
created .build/build/elements/contractslist.wc.js in 10.7s

src/elements/DeployedList/index.ts → .build/build/elements/deployedlist.wc.js...
created .build/build/elements/deployedlist.wc.js in 11.9s

src/elements/FarmingCalculator/index.ts → .build/build/elements/farmingcalculator.wc.js...
created .build/build/elements/farmingcalculator.wc.js in 8.8s

src/elements/Import/index.ts → .build/build/elements/import.wc.js...
created .build/build/elements/import.wc.js in 4.7s

src/elements/Mastodon/index.ts → .build/build/elements/mastodon.wc.js...
created .build/build/elements/mastodon.wc.js in 7.9s

src/elements/Mattermost/index.ts → .build/build/elements/mattermost.wc.js...
created .build/build/elements/mattermost.wc.js in 9.6s

src/elements/Notification/index.ts → .build/build/elements/notification.wc.js...
created .build/build/elements/notification.wc.js in 3.3s

src/elements/TFhubValidator/index.ts → .build/build/elements/tfhubvalidator.wc.js...
created .build/build/elements/tfhubvalidator.wc.js in 7.5s

src/elements/algorand/index.ts → .build/build/elements/algorand.wc.js...
created .build/build/elements/algorand.wc.js in 9.8s

src/elements/base/index.ts → .build/build/elements/base.wc.js...
created .build/build/elements/base.wc.js in 5.9s

src/elements/caprover/index.ts → .build/build/elements/caprover.wc.js...
created .build/build/elements/caprover.wc.js in 7.8s

src/elements/casperlabs/index.ts → .build/build/elements/casperlabs.wc.js...
created .build/build/elements/casperlabs.wc.js in 7.3s

src/elements/disclaimer/index.ts → .build/build/elements/disclaimer.wc.js...
created .build/build/elements/disclaimer.wc.js in 2.9s

src/elements/discourse/index.ts → .build/build/elements/discourse.wc.js...
created .build/build/elements/discourse.wc.js in 8.5s

src/elements/fullvm/index.ts → .build/build/elements/fullvm.wc.js...
created .build/build/elements/fullvm.wc.js in 12.1s

src/elements/funkwhale/index.ts → .build/build/elements/funkwhale.wc.js...
created .build/build/elements/funkwhale.wc.js in 7.9s

src/elements/inca/index.ts → .build/build/elements/inca.wc.js...
created .build/build/elements/inca.wc.js in 3s

src/elements/kubernetes/index.ts → .build/build/elements/kubernetes.wc.js...
Killed
error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by mohamedamer453** [comment] 2022-12-04 15:03
Closing this one since it's a duplicate of #1136.
I Encountered the same error as seen in https://github.com/threefoldtech/grid_weblets/issues/1136#issuecomment-1336433044 and it'll be followed in the original issue.

**Closed as completed by mohamedamer453** 2022-12-04 15:03 UTC
Labels: priority_major, type_bug
