### ISSUE TITLE
Got error deploying and still deployed on devnet

### ISSUE THREAD

**Issue by AbdelrahmanElawady** [threefoldtech/grid_weblets#1060] opened 2022-10-20 17:39 UTC
I was trying to deploy Kubernetes on [play.dev.grid.tf](url) got error while deploying:
![image_2022-10-20_18-57-14](https://user-images.githubusercontent.com/60783742/197017748-909fb3c4-1a45-44d6-aaf9-6ea5c504772d.png)
from [gridproxy.dev.grid.tf](url) it still got deployed and I could ssh into the Kubernetes cluster:
![image](https://user-images.githubusercontent.com/60783742/197018178-772c2a3d-fb67-4b62-ac31-7d0fccac3378.png)

**Comment by mohamedamer453** [comment] 2022-11-10 08:20
I wasn't able to reproduce this issue after multiple kubernetes deployments and other deployments on devnet.

the only thing close to the mentioned error is the one the user gets after trying to deploy anything from the weblets with a balance less than 2 tfts and it works as intended and prevents the user from deploying with low balance.

![image](https://user-images.githubusercontent.com/101194226/201035406-72eb4049-6371-4fab-b9ac-72df14d27321.png)

but from what i'm seeing in the screenshot above, low balance is not the case in this issue.

I'll close this issue for now since i wasn't able to reproduce it, but please feel free to reopen this issue with more steps on how to reproduce it or if it occurred again. i'll also keep an eye on this error and reopen this issue in case i encounter it in the future.

**Closed by mohamedamer453** 2022-11-10 08:20 UTC
Labels: state_verification
