### ISSUE TITLE
listing anything but kubernetes hangs on `Loading ...`

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#202] opened 2021-12-13 19:58 UTC
![image](https://user-images.githubusercontent.com/64129/145879577-b19e7dff-60bf-4482-a378-0e73565f4e26.png)

on development branch

**Comment by dmahmouali** [comment] 2021-12-14 10:16
it may be related to this fix https://github.com/threefoldtech/grid_weblets/pull/207

**Comment by AhmedHanafy725** [comment] 2021-12-14 13:46
This can happen when contracts are deleted from the contracts module, not from the k8s module. The reason is grid3_client
- tries to invalidate the cached info about these deployments on the kvstore.
- finds deleted contracts.
- tries to remove the keys for the deleted deployments which are extrinsic calls.
- then tfchain can't handle parallel extrinsic calls.

### suggested solutions

- getting deployment sequentially in weblets.
- implementing a locking on applying extrinsic in grid3_client.

**Comment by xmonader** [comment] 2021-12-15 10:13
I actually removed some contracts from the polka UI, but Kubernetes didn't have anything to start with, all of the contracts I deleted were for VMs

**Comment by MohamedElmdary** [comment] 2021-12-16 08:28
@AhmedHanafy725 
> * getting deployment sequentially in weblets.
This would take too much time to get deployments one by one

**Comment by abom** [comment] 2021-12-16 10:24
I'm still getting this, only used weblets recently to deal with deployments


![Screenshot from 2021-12-16 12-22-31](https://user-images.githubusercontent.com/511438/146353956-4ef36ba5-247d-4eed-95b1-a0f9b9bd0c06.png)

**Comment by AhmedHanafy725** [comment] 2021-12-16 10:28
me also 
![image](https://user-images.githubusercontent.com/41957921/146354550-fcc76a48-0df3-415d-b2f2-a62a7da81aef.png)

**Comment by AhmedHanafy725** [comment] 2021-12-16 10:32
### How to reproduce 
- deploy 2 VMs
- cancel the contracts from the contracts tab
- after it finishes canceling, go to the VMs tab again

**Comment by AhmedHanafy725** [comment] 2021-12-16 15:40
Done fixed on grid3_client by locking the extrinsic, but it needs to upgrade the client version to 0.0.35.

**Comment by mhost39** [comment] 2021-12-16 16:19
Verified 
![image](https://user-images.githubusercontent.com/31102305/146408747-8ab4ab6a-e3aa-406e-9a8d-683b3dfe1b3f.png)

**Closed by mhost39** 2021-12-16 16:19 UTC
Labels: priority_major, type_bug
