### ISSUE TITLE
Resource validation not working on testnet

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/grid_weblets#1448] opened 2023-04-07 21:48 UTC
On testnet playground, validation for node resources is not working properly. I'm able to specify more resources than the node has available (or at all), and no error is shown:

![image](https://user-images.githubusercontent.com/17682591/230682391-2492ca9a-0bf0-4cda-90c0-42624464fe61.png)
 
Compare to what's available:

![image](https://user-images.githubusercontent.com/17682591/230682460-83386f5a-e386-4da9-b657-16415a9337ff.png)

Message is shown as expected if I increase RAM to 256gb:

![image](https://user-images.githubusercontent.com/17682591/230682540-f2fd0d57-5c91-46cd-af3d-5fee49d69067.png)

**Comment by scottyeager** [comment] 2023-04-07 22:31
A bit more info:

* CPUs are over provisioning, I guess, so that part is okay (except that it's bad UX to allow the user to reserve 32 cpus on a machine that has fewer)
* The RAM and SSD sometimes validate correctly, but by playing with the values it's possible to break it again
* To see the issue in action, just try changing some values for RAM and SSD into the available range and then back out

**Comment by ramezsaeed** [comment] 2023-04-12 13:42
Fixed in 3.10.0

**Comment by mohamedamer453** [comment] 2023-04-13 10:48
I've been trying to reproduce this on devnet weblets `01de9dc` for a while now with multiple configurations for `CPU`, `Memory`, `Disk Size` but i was not able to. the validation seems to be working as intended and the capacity filter only returns nodes that have enough resources.

[Screencast from 13-04-23 12:35:57.webm](https://user-images.githubusercontent.com/101194226/231734958-a9689c60-6bd9-46fd-8131-a61ed968569a.webm)

And the manual filter reports correctly that the node doesn't have enough resources when the enter resources exceeds the available ones.

[Screencast from 13-04-23 12:42:36.webm](https://user-images.githubusercontent.com/101194226/231735377-a8f67fe1-ef51-46ce-b28b-a57156a25513.webm)

> 
> * The RAM and SSD sometimes validate correctly, but by playing with the values it's possible to break it again
> * To see the issue in action, just try changing some values for RAM and SSD into the available range and then back out

I've tried playing with all of the values to break it but it didn't work.

I'll close this issue for now since i wasn't able to reproduce it. but it would be great if you could give it a try on the latest devnet weblets and if it was reproducible with you please reopen this issue with steps on how to reproduce.

**Closed as completed by mohamedamer453** 2023-04-13 10:48 UTC
Labels: type_bug
