### ISSUE TITLE
Can not ssh to machine on devnet

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/grid_weblets#633] opened 2022-04-04 10:34 UTC
### Description

I deployed a machine on devnet using weblets, but for some reason I can not ssh to it although my key is provided in the env vars
it asks for password, tried it two times same issue happened

### Steps to reproduce

deploy a virtual machine from weblets
![Screenshot from 2022-04-04 12-30-06](https://user-images.githubusercontent.com/1689456/161526552-22ae46d7-1bc4-4531-a335-8f3b851e8218.png)

**Comment by AhmedHanafy725** [comment] 2022-04-04 10:41
which image was used? also, can you provide the deployment object?

**Comment by ashraffouda** [comment] 2022-04-04 10:54
the default image `tf-official-apps/threefoldtech-ubuntu-20.04`
deployment object 
```

{
    "version": 0,
    "contractId": 9461,
    "nodeId": 3,
    "name": "Cosmos",
    "created": 1649068002,
    "status": "ok",
    "message": "",
    "flist": "https://hub.grid.tf/tf-official-apps/threefoldtech-ubuntu-20.04.flist",
    "publicIP": null,
    "planetary": "300:d205:aee5:1d1e:1fc3:b1af:dd8a:9082",
    "interfaces": [
        {
            "network": "NWf6effa41",
            "ip": "10.20.2.2"
        }
    ],
    "capacity": {
        "cpu": 4,
        "memory": 4096
    },
    "mounts": [
        {
            "name": "cosmos",
            "mountPoint": "/mnt/cosmos",
            "size": 53687091200,
            "state": "ok",
            "message": ""
        }
    ],
    "env": {
        "SSH_KEY": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDTwULSsUubOq3VPWL6cdrDvexDmjfznGydFPyaNcn7gAL9lRxwFbCDPMj7MbhNSpxxHV2+/iJPQOTVJu4oc1N7bPP3gBCnF51rPrhTpGCt5pBbTzeyNweanhedkKDsCO2mIEh/92Od5Hg512dX4j7Zw6ipRWYSaepapfyoRnNSriW/s3DH/uewezVtL5EuypMdfNngV/u2KZYWoeiwhrY/yEUykQVUwDysW/xUJNP5o+KSTAvNSJatr3FbuCFuCjBSvageOLHePTeUwu6qjqe+Xs4piF1ByO/6cOJ8bt5Vcx0bAtI8/MPApplUU/JWevsPNApvnA/ntffI+u8DCwgP"
    },
    "entrypoint": "/init.sh",
    "metadata": "",
    "description": "",
    "corex": false
}
```

**Comment by abom** [comment] 2022-04-28 10:11
@ashraffouda this deployment is still out there, could you reproduce again?

**Comment by mohamedamer453** [comment] 2022-05-05 10:54
Verified on devnet 

I deployed a vm and i was able to ssh to that VM with yigg IP and public IP without any issues.

Closing this for now since i wasn't able to reproduce it. Please reopen if it is still an issue or you were able to reproduce it.

**Closed by mohamedamer453** 2022-05-05 10:54 UTC
