### ISSUE TITLE
Deployment of VM fails on testnet

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/grid_weblets#622] opened 2022-03-28 05:53 UTC
When deploying VM on a testnet, the deployment times out and keeps showing a loader and nothing happens over a period of time.

Previously the VM was deployed without any issues and timeouts

![weblets_vm_deployment1](https://user-images.githubusercontent.com/65153287/160334759-214511c2-124c-456f-9cc7-2e6b317f5d82.png)

**Comment by mohamedamer453** [comment] 2022-05-05 09:36
Verified on testnet weblets v1.4.1-rc2

The issue is fixed on this version of weblets and i successfully deployed a VM without any issues.

![image](https://user-images.githubusercontent.com/101194226/166896709-ee5250e9-d1da-483c-b929-931129f471d7.png)

VM Details

```
{
    "version": 0,
    "contractId": 4303,
    "nodeId": 3,
    "name": "VM48389bf8",
    "created": 1651742893,
    "status": "ok",
    "message": "",
    "flist": "https://hub.grid.tf/tf-official-apps/threefoldtech-ubuntu-20.04.flist",
    "publicIP": null,
    "planetary": "302:1eb4:b62c:8ba6:b48b:24aa:22e2:2fd1",
    "interfaces": [
        {
            "network": "NW6f69f027",
            "ip": "10.20.2.2"
        }
    ],
    "capacity": {
        "cpu": 4,
        "memory": 8192
    },
    "mounts": [],
    "env": {
        "SSH_KEY": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC533B35CELELtgg2d7Tsi5KelLxR0FYUlrcTmRRQuTNP9arP01JYD8iHKqh6naMbbzR8+M0gdPEeRK4oVqQtEcH1C47vLyRI/4DqahAE2nTW08wtJM5uiIvcQ9H2HMzZ3MXYWWlgyHMgW2QXQxzrRS0NXvsY+4wxe97MMZs9MDs+d+X15DfG6JffjMHydi+4tHB50WmHe5tFscBFxLbgDBUxNGiwi3BQc1nWIuYwMMV1GFwT3ndyLAp19KPkEa/dffiqLdzkgs2qpXtfBhTZ/lFeQRc60DHCMWExr9ySDbavIMuBFylf/ZQeJXm9dFXJN7bBTbflZIIuUMjmrI7cU5eSuZqAj5l+Yb1mLN8ljmKSIM3/tkKbzXNH5AUtRVKTn+aEPvJAEYtserAxAP5pjy6nmegn0UerEE3DWEV2kqDig3aPSNhi9WSCykvG2tz7DIr0UP6qEIWYMC/5OisnSGj8w8dAjyxS9B0Jlx7DEmqPDNBqp8UcwV75Cot8vtIac= root@mohamed-Inspiron-3576"
    },
    "entrypoint": "/init.sh",
    "metadata": "",
    "description": "",
    "corex": false
}
```

**Closed by mohamedamer453** 2022-05-05 09:36 UTC
